"""Validated ASR sidecar cache metadata.

User-authored SRT files remain valid without metadata.  SRT files generated by
LiveClipper carry this metadata so replacing a source video at the same path
cannot silently reuse stale subtitles or word timings.
"""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
from typing import Any


CACHE_SCHEMA_VERSION = 1
FINGERPRINT_METHOD = "sampled-sha256-v1"
_SAMPLE_SIZE = 1024 * 1024


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def source_fingerprint(source_path: str | os.PathLike[str]) -> dict[str, Any]:
    """Return a fast content fingerprint using spaced samples plus file size."""
    path = Path(source_path).resolve()
    stat = path.stat()
    size = int(stat.st_size)
    offsets = sorted({0, max(0, size // 2 - _SAMPLE_SIZE // 2), max(0, size - _SAMPLE_SIZE)})
    digest = hashlib.sha256()
    digest.update(FINGERPRINT_METHOD.encode("ascii"))
    digest.update(str(size).encode("ascii"))
    with path.open("rb") as source:
        for offset in offsets:
            source.seek(offset)
            chunk = source.read(min(_SAMPLE_SIZE, max(0, size - offset)))
            digest.update(str(offset).encode("ascii"))
            digest.update(len(chunk).to_bytes(8, "big"))
            digest.update(chunk)
    return {
        "method": FINGERPRINT_METHOD,
        "size": size,
        "mtime_ns": int(stat.st_mtime_ns),
        "digest": digest.hexdigest(),
    }


def metadata_path(srt_path: str | os.PathLike[str]) -> Path:
    return Path(srt_path).with_suffix(".asr-cache.json")


def word_timing_path(srt_path: str | os.PathLike[str]) -> Path:
    return Path(srt_path).with_suffix(".words.json")


def write_metadata(
    source_path: str | os.PathLike[str],
    srt_path: str | os.PathLike[str],
    *,
    provider: str,
    model: str = "",
    timing_precision: str = "segment",
) -> Path:
    source = Path(source_path).resolve()
    srt = Path(srt_path).resolve()
    if not source.is_file() or not srt.is_file():
        raise FileNotFoundError("ASR cache source or SRT is missing")
    words = word_timing_path(srt)
    payload = {
        "schema_version": CACHE_SCHEMA_VERSION,
        "source": source_fingerprint(source),
        "asr": {
            "provider": str(provider or "unknown"),
            "model": str(model or ""),
            "timing_precision": str(timing_precision or "segment"),
        },
        "outputs": {
            "srt_sha256": _sha256_file(srt),
            "words_sha256": _sha256_file(words) if words.is_file() else "",
        },
    }
    destination = metadata_path(srt)
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_name(f".{destination.name}.{os.getpid()}.tmp")
    temporary.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    os.replace(temporary, destination)
    return destination


def inspect_cache(
    source_path: str | os.PathLike[str],
    srt_path: str | os.PathLike[str],
) -> dict[str, Any]:
    """Inspect a sidecar without rejecting unmanaged, user-authored SRT files."""
    source = Path(source_path)
    srt = Path(srt_path)
    metadata = metadata_path(srt)
    if not srt.is_file() or srt.stat().st_size <= 0:
        return {"valid": False, "managed": metadata.is_file(), "reason": "srt_missing"}
    if not metadata.is_file():
        return {"valid": True, "managed": False, "reason": "user_or_legacy_srt"}
    try:
        payload = json.loads(metadata.read_text(encoding="utf-8-sig"))
        if not isinstance(payload, dict) or payload.get("schema_version") != CACHE_SCHEMA_VERSION:
            raise ValueError("unsupported metadata schema")
        expected_source = payload.get("source")
        actual_source = source_fingerprint(source)
        if not isinstance(expected_source, dict):
            raise ValueError("source fingerprint is missing")
        if (
            expected_source.get("method") != actual_source["method"]
            or int(expected_source.get("size", -1)) != actual_source["size"]
            or str(expected_source.get("digest") or "") != actual_source["digest"]
        ):
            return {"valid": False, "managed": True, "reason": "source_changed"}
        outputs = payload.get("outputs")
        if not isinstance(outputs, dict) or outputs.get("srt_sha256") != _sha256_file(srt):
            return {"valid": False, "managed": True, "reason": "srt_changed"}
        words_digest = str(outputs.get("words_sha256") or "")
        words = word_timing_path(srt)
        if words_digest and (not words.is_file() or _sha256_file(words) != words_digest):
            return {"valid": False, "managed": True, "reason": "words_changed"}
        asr = payload.get("asr") if isinstance(payload.get("asr"), dict) else {}
        return {
            "valid": True,
            "managed": True,
            "reason": "verified",
            "provider": str(asr.get("provider") or "unknown"),
            "model": str(asr.get("model") or ""),
            "timing_precision": str(asr.get("timing_precision") or "segment"),
        }
    except Exception as exc:
        return {
            "valid": False,
            "managed": True,
            "reason": "metadata_invalid",
            "detail": f"{type(exc).__name__}: {exc}",
        }
